// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gate.proto

#include "gate.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace frmpub {
	namespace protocc {
		constexpr register_gate_dbvisit_c::register_gate_dbvisit_c(
			::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
			: sif_(nullptr) {
		}
		struct register_gate_dbvisit_cDefaultTypeInternal {
			constexpr register_gate_dbvisit_cDefaultTypeInternal()
				: _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {
			}
			~register_gate_dbvisit_cDefaultTypeInternal() {}
			union {
				register_gate_dbvisit_c _instance;
			};
		};
		PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT register_gate_dbvisit_cDefaultTypeInternal _register_gate_dbvisit_c_default_instance_;
		constexpr register_gate_dbvisit_s::register_gate_dbvisit_s(
			::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
			: result_(0) {
		}
		struct register_gate_dbvisit_sDefaultTypeInternal {
			constexpr register_gate_dbvisit_sDefaultTypeInternal()
				: _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {
			}
			~register_gate_dbvisit_sDefaultTypeInternal() {}
			union {
				register_gate_dbvisit_s _instance;
			};
		};
		PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT register_gate_dbvisit_sDefaultTypeInternal _register_gate_dbvisit_s_default_instance_;
		constexpr register_gate_world_c::register_gate_world_c(
			::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
			: sif_(nullptr) {
		}
		struct register_gate_world_cDefaultTypeInternal {
			constexpr register_gate_world_cDefaultTypeInternal()
				: _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {
			}
			~register_gate_world_cDefaultTypeInternal() {}
			union {
				register_gate_world_c _instance;
			};
		};
		PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT register_gate_world_cDefaultTypeInternal _register_gate_world_c_default_instance_;
		constexpr register_gate_world_s::register_gate_world_s(
			::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
			: sifs_()
			, result_(0) {
		}
		struct register_gate_world_sDefaultTypeInternal {
			constexpr register_gate_world_sDefaultTypeInternal()
				: _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {
			}
			~register_gate_world_sDefaultTypeInternal() {}
			union {
				register_gate_world_s _instance;
			};
		};
		PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT register_gate_world_sDefaultTypeInternal _register_gate_world_s_default_instance_;
		constexpr register_gate_login_c::register_gate_login_c(
			::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
			: sif_(nullptr) {
		}
		struct register_gate_login_cDefaultTypeInternal {
			constexpr register_gate_login_cDefaultTypeInternal()
				: _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {
			}
			~register_gate_login_cDefaultTypeInternal() {}
			union {
				register_gate_login_c _instance;
			};
		};
		PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT register_gate_login_cDefaultTypeInternal _register_gate_login_c_default_instance_;
		constexpr register_gate_login_s::register_gate_login_s(
			::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
			: result_(0) {
		}
		struct register_gate_login_sDefaultTypeInternal {
			constexpr register_gate_login_sDefaultTypeInternal()
				: _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {
			}
			~register_gate_login_sDefaultTypeInternal() {}
			union {
				register_gate_login_s _instance;
			};
		};
		PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT register_gate_login_sDefaultTypeInternal _register_gate_login_s_default_instance_;
		constexpr register_gate_game_c::register_gate_game_c(
			::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
			: sif_(nullptr) {
		}
		struct register_gate_game_cDefaultTypeInternal {
			constexpr register_gate_game_cDefaultTypeInternal()
				: _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {
			}
			~register_gate_game_cDefaultTypeInternal() {}
			union {
				register_gate_game_c _instance;
			};
		};
		PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT register_gate_game_cDefaultTypeInternal _register_gate_game_c_default_instance_;
		constexpr register_gate_game_s::register_gate_game_s(
			::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
			: result_(0) {
		}
		struct register_gate_game_sDefaultTypeInternal {
			constexpr register_gate_game_sDefaultTypeInternal()
				: _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {
			}
			~register_gate_game_sDefaultTypeInternal() {}
			union {
				register_gate_game_s _instance;
			};
		};
		PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT register_gate_game_sDefaultTypeInternal _register_gate_game_s_default_instance_;
		constexpr clioffline_gate_all_c::clioffline_gate_all_c(
			::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
			: aid_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
			, ip_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
			, port_(0) {
		}
		struct clioffline_gate_all_cDefaultTypeInternal {
			constexpr clioffline_gate_all_cDefaultTypeInternal()
				: _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {
			}
			~clioffline_gate_all_cDefaultTypeInternal() {}
			union {
				clioffline_gate_all_c _instance;
			};
		};
		PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT clioffline_gate_all_cDefaultTypeInternal _clioffline_gate_all_c_default_instance_;
	}  // namespace protocc
}  // namespace frmpub
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_gate_2eproto[9];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_gate_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_gate_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_gate_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::frmpub::protocc::register_gate_dbvisit_c, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::frmpub::protocc::register_gate_dbvisit_c, sif_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::frmpub::protocc::register_gate_dbvisit_s, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::frmpub::protocc::register_gate_dbvisit_s, result_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::frmpub::protocc::register_gate_world_c, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::frmpub::protocc::register_gate_world_c, sif_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::frmpub::protocc::register_gate_world_s, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::frmpub::protocc::register_gate_world_s, result_),
  PROTOBUF_FIELD_OFFSET(::frmpub::protocc::register_gate_world_s, sifs_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::frmpub::protocc::register_gate_login_c, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::frmpub::protocc::register_gate_login_c, sif_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::frmpub::protocc::register_gate_login_s, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::frmpub::protocc::register_gate_login_s, result_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::frmpub::protocc::register_gate_game_c, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::frmpub::protocc::register_gate_game_c, sif_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::frmpub::protocc::register_gate_game_s, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::frmpub::protocc::register_gate_game_s, result_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::frmpub::protocc::clioffline_gate_all_c, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::frmpub::protocc::clioffline_gate_all_c, aid_),
  PROTOBUF_FIELD_OFFSET(::frmpub::protocc::clioffline_gate_all_c, ip_),
  PROTOBUF_FIELD_OFFSET(::frmpub::protocc::clioffline_gate_all_c, port_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::frmpub::protocc::register_gate_dbvisit_c)},
  { 6, -1, sizeof(::frmpub::protocc::register_gate_dbvisit_s)},
  { 12, -1, sizeof(::frmpub::protocc::register_gate_world_c)},
  { 18, -1, sizeof(::frmpub::protocc::register_gate_world_s)},
  { 25, -1, sizeof(::frmpub::protocc::register_gate_login_c)},
  { 31, -1, sizeof(::frmpub::protocc::register_gate_login_s)},
  { 37, -1, sizeof(::frmpub::protocc::register_gate_game_c)},
  { 43, -1, sizeof(::frmpub::protocc::register_gate_game_s)},
  { 49, -1, sizeof(::frmpub::protocc::clioffline_gate_all_c)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const* const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::frmpub::protocc::_register_gate_dbvisit_c_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::frmpub::protocc::_register_gate_dbvisit_s_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::frmpub::protocc::_register_gate_world_c_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::frmpub::protocc::_register_gate_world_s_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::frmpub::protocc::_register_gate_login_c_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::frmpub::protocc::_register_gate_login_s_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::frmpub::protocc::_register_gate_game_c_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::frmpub::protocc::_register_gate_game_s_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::frmpub::protocc::_clioffline_gate_all_c_default_instance_),
};

const char descriptor_table_protodef_gate_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
"\n\ngate.proto\022\016frmpub.protocc\032\014common.pro"
"to\"B\n\027register_gate_dbvisit_c\022\'\n\003sif\030\001 \001"
"(\0132\032.frmpub.protocc.ServerInfo\")\n\027regist"
"er_gate_dbvisit_s\022\016\n\006result\030\001 \001(\005\"@\n\025reg"
"ister_gate_world_c\022\'\n\003sif\030\001 \001(\0132\032.frmpub"
".protocc.ServerInfo\"Q\n\025register_gate_wor"
"ld_s\022\016\n\006result\030\001 \001(\005\022(\n\004sifs\030\002 \003(\0132\032.frm"
"pub.protocc.ServerInfo\"@\n\025register_gate_"
"login_c\022\'\n\003sif\030\001 \001(\0132\032.frmpub.protocc.Se"
"rverInfo\"\'\n\025register_gate_login_s\022\016\n\006res"
"ult\030\001 \001(\005\"\?\n\024register_gate_game_c\022\'\n\003sif"
"\030\001 \001(\0132\032.frmpub.protocc.ServerInfo\"&\n\024re"
"gister_gate_game_s\022\016\n\006result\030\001 \001(\005\">\n\025cl"
"ioffline_gate_all_c\022\013\n\003aid\030\001 \001(\t\022\n\n\002ip\030\002"
" \001(\t\022\014\n\004port\030\003 \001(\005b\006proto3"
;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* const descriptor_table_gate_2eproto_deps[1] = {
  &::descriptor_table_common_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_gate_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_gate_2eproto = {
  false, false, 586, descriptor_table_protodef_gate_2eproto, "gate.proto",
  &descriptor_table_gate_2eproto_once, descriptor_table_gate_2eproto_deps, 1, 9,
  schemas, file_default_instances, TableStruct_gate_2eproto::offsets,
  file_level_metadata_gate_2eproto, file_level_enum_descriptors_gate_2eproto, file_level_service_descriptors_gate_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK::PROTOBUF_NAMESPACE_ID::Metadata
descriptor_table_gate_2eproto_metadata_getter(int index) {
	::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_gate_2eproto);
	return descriptor_table_gate_2eproto.file_level_metadata[index];
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_gate_2eproto(&descriptor_table_gate_2eproto);
namespace frmpub {
	namespace protocc {

		// ===================================================================

		class register_gate_dbvisit_c::_Internal {
		public:
			static const ::frmpub::protocc::ServerInfo& sif(const register_gate_dbvisit_c* msg);
		};

		const ::frmpub::protocc::ServerInfo&
			register_gate_dbvisit_c::_Internal::sif(const register_gate_dbvisit_c* msg) {
			return *msg->sif_;
		}
		void register_gate_dbvisit_c::clear_sif() {
			if (GetArena() == nullptr && sif_ != nullptr) {
				delete sif_;
			}
			sif_ = nullptr;
		}
		register_gate_dbvisit_c::register_gate_dbvisit_c(::PROTOBUF_NAMESPACE_ID::Arena* arena)
			: ::PROTOBUF_NAMESPACE_ID::Message(arena) {
			SharedCtor();
			RegisterArenaDtor(arena);
			// @@protoc_insertion_point(arena_constructor:frmpub.protocc.register_gate_dbvisit_c)
		}
		register_gate_dbvisit_c::register_gate_dbvisit_c(const register_gate_dbvisit_c& from)
			: ::PROTOBUF_NAMESPACE_ID::Message() {
			_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
			if (from._internal_has_sif()) {
				sif_ = new ::frmpub::protocc::ServerInfo(*from.sif_);
			}
			else {
				sif_ = nullptr;
			}
			// @@protoc_insertion_point(copy_constructor:frmpub.protocc.register_gate_dbvisit_c)
		}

		void register_gate_dbvisit_c::SharedCtor() {
			sif_ = nullptr;
		}

		register_gate_dbvisit_c::~register_gate_dbvisit_c() {
			// @@protoc_insertion_point(destructor:frmpub.protocc.register_gate_dbvisit_c)
			SharedDtor();
			_internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
		}

		void register_gate_dbvisit_c::SharedDtor() {
			GOOGLE_DCHECK(GetArena() == nullptr);
			if (this != internal_default_instance()) delete sif_;
		}

		void register_gate_dbvisit_c::ArenaDtor(void* object) {
			register_gate_dbvisit_c* _this = reinterpret_cast<register_gate_dbvisit_c*>(object);
			(void)_this;
		}
		void register_gate_dbvisit_c::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
		}
		void register_gate_dbvisit_c::SetCachedSize(int size) const {
			_cached_size_.Set(size);
		}

		void register_gate_dbvisit_c::Clear() {
			// @@protoc_insertion_point(message_clear_start:frmpub.protocc.register_gate_dbvisit_c)
			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			// Prevent compiler warnings about cached_has_bits being unused
			(void)cached_has_bits;

			if (GetArena() == nullptr && sif_ != nullptr) {
				delete sif_;
			}
			sif_ = nullptr;
			_internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
		}

		const char* register_gate_dbvisit_c::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
			while (!ctx->Done(&ptr)) {
				::PROTOBUF_NAMESPACE_ID::uint32 tag;
				ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
				CHK_(ptr);
				switch (tag >> 3) {
					// .frmpub.protocc.ServerInfo sif = 1;
				case 1:
					if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
						ptr = ctx->ParseMessage(_internal_mutable_sif(), ptr);
						CHK_(ptr);
					}
					else goto handle_unusual;
					continue;
				default:
				{
				handle_unusual:
					if ((tag & 7) == 4 || tag == 0) {
						ctx->SetLastTag(tag);
						goto success;
					}
					ptr = UnknownFieldParse(tag,
						_internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
						ptr, ctx);
					CHK_(ptr != nullptr);
					continue;
				}
				}  // switch
			}  // while
		success:
			return ptr;
		failure:
			ptr = nullptr;
			goto success;
#undef CHK_
		}

		::PROTOBUF_NAMESPACE_ID::uint8* register_gate_dbvisit_c::_InternalSerialize(
			::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
			// @@protoc_insertion_point(serialize_to_array_start:frmpub.protocc.register_gate_dbvisit_c)
			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			(void)cached_has_bits;

			// .frmpub.protocc.ServerInfo sif = 1;
			if (this->has_sif()) {
				target = stream->EnsureSpace(target);
				target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
					InternalWriteMessage(
						1, _Internal::sif(this), target, stream);
			}

			if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
				target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
					_internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
			}
			// @@protoc_insertion_point(serialize_to_array_end:frmpub.protocc.register_gate_dbvisit_c)
			return target;
		}

		size_t register_gate_dbvisit_c::ByteSizeLong() const {
			// @@protoc_insertion_point(message_byte_size_start:frmpub.protocc.register_gate_dbvisit_c)
			size_t total_size = 0;

			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			// Prevent compiler warnings about cached_has_bits being unused
			(void)cached_has_bits;

			// .frmpub.protocc.ServerInfo sif = 1;
			if (this->has_sif()) {
				total_size += 1 +
					::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
						*sif_);
			}

			if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
				return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
					_internal_metadata_, total_size, &_cached_size_);
			}
			int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
			SetCachedSize(cached_size);
			return total_size;
		}

		void register_gate_dbvisit_c::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
			// @@protoc_insertion_point(generalized_merge_from_start:frmpub.protocc.register_gate_dbvisit_c)
			GOOGLE_DCHECK_NE(&from, this);
			const register_gate_dbvisit_c* source =
				::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<register_gate_dbvisit_c>(
					&from);
			if (source == nullptr) {
				// @@protoc_insertion_point(generalized_merge_from_cast_fail:frmpub.protocc.register_gate_dbvisit_c)
				::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
			}
			else {
				// @@protoc_insertion_point(generalized_merge_from_cast_success:frmpub.protocc.register_gate_dbvisit_c)
				MergeFrom(*source);
			}
		}

		void register_gate_dbvisit_c::MergeFrom(const register_gate_dbvisit_c& from) {
			// @@protoc_insertion_point(class_specific_merge_from_start:frmpub.protocc.register_gate_dbvisit_c)
			GOOGLE_DCHECK_NE(&from, this);
			_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			(void)cached_has_bits;

			if (from.has_sif()) {
				_internal_mutable_sif()->::frmpub::protocc::ServerInfo::MergeFrom(from._internal_sif());
			}
		}

		void register_gate_dbvisit_c::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
			// @@protoc_insertion_point(generalized_copy_from_start:frmpub.protocc.register_gate_dbvisit_c)
			if (&from == this) return;
			Clear();
			MergeFrom(from);
		}

		void register_gate_dbvisit_c::CopyFrom(const register_gate_dbvisit_c& from) {
			// @@protoc_insertion_point(class_specific_copy_from_start:frmpub.protocc.register_gate_dbvisit_c)
			if (&from == this) return;
			Clear();
			MergeFrom(from);
		}

		bool register_gate_dbvisit_c::IsInitialized() const {
			return true;
		}

		void register_gate_dbvisit_c::InternalSwap(register_gate_dbvisit_c* other) {
			using std::swap;
			_internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
			swap(sif_, other->sif_);
		}

		::PROTOBUF_NAMESPACE_ID::Metadata register_gate_dbvisit_c::GetMetadata() const {
			return GetMetadataStatic();
		}


		// ===================================================================

		class register_gate_dbvisit_s::_Internal {
		public:
		};

		register_gate_dbvisit_s::register_gate_dbvisit_s(::PROTOBUF_NAMESPACE_ID::Arena* arena)
			: ::PROTOBUF_NAMESPACE_ID::Message(arena) {
			SharedCtor();
			RegisterArenaDtor(arena);
			// @@protoc_insertion_point(arena_constructor:frmpub.protocc.register_gate_dbvisit_s)
		}
		register_gate_dbvisit_s::register_gate_dbvisit_s(const register_gate_dbvisit_s& from)
			: ::PROTOBUF_NAMESPACE_ID::Message() {
			_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
			result_ = from.result_;
			// @@protoc_insertion_point(copy_constructor:frmpub.protocc.register_gate_dbvisit_s)
		}

		void register_gate_dbvisit_s::SharedCtor() {
			result_ = 0;
		}

		register_gate_dbvisit_s::~register_gate_dbvisit_s() {
			// @@protoc_insertion_point(destructor:frmpub.protocc.register_gate_dbvisit_s)
			SharedDtor();
			_internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
		}

		void register_gate_dbvisit_s::SharedDtor() {
			GOOGLE_DCHECK(GetArena() == nullptr);
		}

		void register_gate_dbvisit_s::ArenaDtor(void* object) {
			register_gate_dbvisit_s* _this = reinterpret_cast<register_gate_dbvisit_s*>(object);
			(void)_this;
		}
		void register_gate_dbvisit_s::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
		}
		void register_gate_dbvisit_s::SetCachedSize(int size) const {
			_cached_size_.Set(size);
		}

		void register_gate_dbvisit_s::Clear() {
			// @@protoc_insertion_point(message_clear_start:frmpub.protocc.register_gate_dbvisit_s)
			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			// Prevent compiler warnings about cached_has_bits being unused
			(void)cached_has_bits;

			result_ = 0;
			_internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
		}

		const char* register_gate_dbvisit_s::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
			while (!ctx->Done(&ptr)) {
				::PROTOBUF_NAMESPACE_ID::uint32 tag;
				ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
				CHK_(ptr);
				switch (tag >> 3) {
					// int32 result = 1;
				case 1:
					if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
						result_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
						CHK_(ptr);
					}
					else goto handle_unusual;
					continue;
				default:
				{
				handle_unusual:
					if ((tag & 7) == 4 || tag == 0) {
						ctx->SetLastTag(tag);
						goto success;
					}
					ptr = UnknownFieldParse(tag,
						_internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
						ptr, ctx);
					CHK_(ptr != nullptr);
					continue;
				}
				}  // switch
			}  // while
		success:
			return ptr;
		failure:
			ptr = nullptr;
			goto success;
#undef CHK_
		}

		::PROTOBUF_NAMESPACE_ID::uint8* register_gate_dbvisit_s::_InternalSerialize(
			::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
			// @@protoc_insertion_point(serialize_to_array_start:frmpub.protocc.register_gate_dbvisit_s)
			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			(void)cached_has_bits;

			// int32 result = 1;
			if (this->result() != 0) {
				target = stream->EnsureSpace(target);
				target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_result(), target);
			}

			if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
				target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
					_internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
			}
			// @@protoc_insertion_point(serialize_to_array_end:frmpub.protocc.register_gate_dbvisit_s)
			return target;
		}

		size_t register_gate_dbvisit_s::ByteSizeLong() const {
			// @@protoc_insertion_point(message_byte_size_start:frmpub.protocc.register_gate_dbvisit_s)
			size_t total_size = 0;

			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			// Prevent compiler warnings about cached_has_bits being unused
			(void)cached_has_bits;

			// int32 result = 1;
			if (this->result() != 0) {
				total_size += 1 +
					::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
						this->_internal_result());
			}

			if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
				return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
					_internal_metadata_, total_size, &_cached_size_);
			}
			int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
			SetCachedSize(cached_size);
			return total_size;
		}

		void register_gate_dbvisit_s::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
			// @@protoc_insertion_point(generalized_merge_from_start:frmpub.protocc.register_gate_dbvisit_s)
			GOOGLE_DCHECK_NE(&from, this);
			const register_gate_dbvisit_s* source =
				::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<register_gate_dbvisit_s>(
					&from);
			if (source == nullptr) {
				// @@protoc_insertion_point(generalized_merge_from_cast_fail:frmpub.protocc.register_gate_dbvisit_s)
				::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
			}
			else {
				// @@protoc_insertion_point(generalized_merge_from_cast_success:frmpub.protocc.register_gate_dbvisit_s)
				MergeFrom(*source);
			}
		}

		void register_gate_dbvisit_s::MergeFrom(const register_gate_dbvisit_s& from) {
			// @@protoc_insertion_point(class_specific_merge_from_start:frmpub.protocc.register_gate_dbvisit_s)
			GOOGLE_DCHECK_NE(&from, this);
			_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			(void)cached_has_bits;

			if (from.result() != 0) {
				_internal_set_result(from._internal_result());
			}
		}

		void register_gate_dbvisit_s::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
			// @@protoc_insertion_point(generalized_copy_from_start:frmpub.protocc.register_gate_dbvisit_s)
			if (&from == this) return;
			Clear();
			MergeFrom(from);
		}

		void register_gate_dbvisit_s::CopyFrom(const register_gate_dbvisit_s& from) {
			// @@protoc_insertion_point(class_specific_copy_from_start:frmpub.protocc.register_gate_dbvisit_s)
			if (&from == this) return;
			Clear();
			MergeFrom(from);
		}

		bool register_gate_dbvisit_s::IsInitialized() const {
			return true;
		}

		void register_gate_dbvisit_s::InternalSwap(register_gate_dbvisit_s* other) {
			using std::swap;
			_internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
			swap(result_, other->result_);
		}

		::PROTOBUF_NAMESPACE_ID::Metadata register_gate_dbvisit_s::GetMetadata() const {
			return GetMetadataStatic();
		}


		// ===================================================================

		class register_gate_world_c::_Internal {
		public:
			static const ::frmpub::protocc::ServerInfo& sif(const register_gate_world_c* msg);
		};

		const ::frmpub::protocc::ServerInfo&
			register_gate_world_c::_Internal::sif(const register_gate_world_c* msg) {
			return *msg->sif_;
		}
		void register_gate_world_c::clear_sif() {
			if (GetArena() == nullptr && sif_ != nullptr) {
				delete sif_;
			}
			sif_ = nullptr;
		}
		register_gate_world_c::register_gate_world_c(::PROTOBUF_NAMESPACE_ID::Arena* arena)
			: ::PROTOBUF_NAMESPACE_ID::Message(arena) {
			SharedCtor();
			RegisterArenaDtor(arena);
			// @@protoc_insertion_point(arena_constructor:frmpub.protocc.register_gate_world_c)
		}
		register_gate_world_c::register_gate_world_c(const register_gate_world_c& from)
			: ::PROTOBUF_NAMESPACE_ID::Message() {
			_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
			if (from._internal_has_sif()) {
				sif_ = new ::frmpub::protocc::ServerInfo(*from.sif_);
			}
			else {
				sif_ = nullptr;
			}
			// @@protoc_insertion_point(copy_constructor:frmpub.protocc.register_gate_world_c)
		}

		void register_gate_world_c::SharedCtor() {
			sif_ = nullptr;
		}

		register_gate_world_c::~register_gate_world_c() {
			// @@protoc_insertion_point(destructor:frmpub.protocc.register_gate_world_c)
			SharedDtor();
			_internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
		}

		void register_gate_world_c::SharedDtor() {
			GOOGLE_DCHECK(GetArena() == nullptr);
			if (this != internal_default_instance()) delete sif_;
		}

		void register_gate_world_c::ArenaDtor(void* object) {
			register_gate_world_c* _this = reinterpret_cast<register_gate_world_c*>(object);
			(void)_this;
		}
		void register_gate_world_c::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
		}
		void register_gate_world_c::SetCachedSize(int size) const {
			_cached_size_.Set(size);
		}

		void register_gate_world_c::Clear() {
			// @@protoc_insertion_point(message_clear_start:frmpub.protocc.register_gate_world_c)
			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			// Prevent compiler warnings about cached_has_bits being unused
			(void)cached_has_bits;

			if (GetArena() == nullptr && sif_ != nullptr) {
				delete sif_;
			}
			sif_ = nullptr;
			_internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
		}

		const char* register_gate_world_c::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
			while (!ctx->Done(&ptr)) {
				::PROTOBUF_NAMESPACE_ID::uint32 tag;
				ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
				CHK_(ptr);
				switch (tag >> 3) {
					// .frmpub.protocc.ServerInfo sif = 1;
				case 1:
					if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
						ptr = ctx->ParseMessage(_internal_mutable_sif(), ptr);
						CHK_(ptr);
					}
					else goto handle_unusual;
					continue;
				default:
				{
				handle_unusual:
					if ((tag & 7) == 4 || tag == 0) {
						ctx->SetLastTag(tag);
						goto success;
					}
					ptr = UnknownFieldParse(tag,
						_internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
						ptr, ctx);
					CHK_(ptr != nullptr);
					continue;
				}
				}  // switch
			}  // while
		success:
			return ptr;
		failure:
			ptr = nullptr;
			goto success;
#undef CHK_
		}

		::PROTOBUF_NAMESPACE_ID::uint8* register_gate_world_c::_InternalSerialize(
			::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
			// @@protoc_insertion_point(serialize_to_array_start:frmpub.protocc.register_gate_world_c)
			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			(void)cached_has_bits;

			// .frmpub.protocc.ServerInfo sif = 1;
			if (this->has_sif()) {
				target = stream->EnsureSpace(target);
				target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
					InternalWriteMessage(
						1, _Internal::sif(this), target, stream);
			}

			if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
				target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
					_internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
			}
			// @@protoc_insertion_point(serialize_to_array_end:frmpub.protocc.register_gate_world_c)
			return target;
		}

		size_t register_gate_world_c::ByteSizeLong() const {
			// @@protoc_insertion_point(message_byte_size_start:frmpub.protocc.register_gate_world_c)
			size_t total_size = 0;

			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			// Prevent compiler warnings about cached_has_bits being unused
			(void)cached_has_bits;

			// .frmpub.protocc.ServerInfo sif = 1;
			if (this->has_sif()) {
				total_size += 1 +
					::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
						*sif_);
			}

			if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
				return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
					_internal_metadata_, total_size, &_cached_size_);
			}
			int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
			SetCachedSize(cached_size);
			return total_size;
		}

		void register_gate_world_c::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
			// @@protoc_insertion_point(generalized_merge_from_start:frmpub.protocc.register_gate_world_c)
			GOOGLE_DCHECK_NE(&from, this);
			const register_gate_world_c* source =
				::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<register_gate_world_c>(
					&from);
			if (source == nullptr) {
				// @@protoc_insertion_point(generalized_merge_from_cast_fail:frmpub.protocc.register_gate_world_c)
				::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
			}
			else {
				// @@protoc_insertion_point(generalized_merge_from_cast_success:frmpub.protocc.register_gate_world_c)
				MergeFrom(*source);
			}
		}

		void register_gate_world_c::MergeFrom(const register_gate_world_c& from) {
			// @@protoc_insertion_point(class_specific_merge_from_start:frmpub.protocc.register_gate_world_c)
			GOOGLE_DCHECK_NE(&from, this);
			_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			(void)cached_has_bits;

			if (from.has_sif()) {
				_internal_mutable_sif()->::frmpub::protocc::ServerInfo::MergeFrom(from._internal_sif());
			}
		}

		void register_gate_world_c::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
			// @@protoc_insertion_point(generalized_copy_from_start:frmpub.protocc.register_gate_world_c)
			if (&from == this) return;
			Clear();
			MergeFrom(from);
		}

		void register_gate_world_c::CopyFrom(const register_gate_world_c& from) {
			// @@protoc_insertion_point(class_specific_copy_from_start:frmpub.protocc.register_gate_world_c)
			if (&from == this) return;
			Clear();
			MergeFrom(from);
		}

		bool register_gate_world_c::IsInitialized() const {
			return true;
		}

		void register_gate_world_c::InternalSwap(register_gate_world_c* other) {
			using std::swap;
			_internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
			swap(sif_, other->sif_);
		}

		::PROTOBUF_NAMESPACE_ID::Metadata register_gate_world_c::GetMetadata() const {
			return GetMetadataStatic();
		}


		// ===================================================================

		class register_gate_world_s::_Internal {
		public:
		};

		void register_gate_world_s::clear_sifs() {
			sifs_.Clear();
		}
		register_gate_world_s::register_gate_world_s(::PROTOBUF_NAMESPACE_ID::Arena* arena)
			: ::PROTOBUF_NAMESPACE_ID::Message(arena),
			sifs_(arena) {
			SharedCtor();
			RegisterArenaDtor(arena);
			// @@protoc_insertion_point(arena_constructor:frmpub.protocc.register_gate_world_s)
		}
		register_gate_world_s::register_gate_world_s(const register_gate_world_s& from)
			: ::PROTOBUF_NAMESPACE_ID::Message(),
			sifs_(from.sifs_) {
			_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
			result_ = from.result_;
			// @@protoc_insertion_point(copy_constructor:frmpub.protocc.register_gate_world_s)
		}

		void register_gate_world_s::SharedCtor() {
			result_ = 0;
		}

		register_gate_world_s::~register_gate_world_s() {
			// @@protoc_insertion_point(destructor:frmpub.protocc.register_gate_world_s)
			SharedDtor();
			_internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
		}

		void register_gate_world_s::SharedDtor() {
			GOOGLE_DCHECK(GetArena() == nullptr);
		}

		void register_gate_world_s::ArenaDtor(void* object) {
			register_gate_world_s* _this = reinterpret_cast<register_gate_world_s*>(object);
			(void)_this;
		}
		void register_gate_world_s::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
		}
		void register_gate_world_s::SetCachedSize(int size) const {
			_cached_size_.Set(size);
		}

		void register_gate_world_s::Clear() {
			// @@protoc_insertion_point(message_clear_start:frmpub.protocc.register_gate_world_s)
			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			// Prevent compiler warnings about cached_has_bits being unused
			(void)cached_has_bits;

			sifs_.Clear();
			result_ = 0;
			_internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
		}

		const char* register_gate_world_s::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
			while (!ctx->Done(&ptr)) {
				::PROTOBUF_NAMESPACE_ID::uint32 tag;
				ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
				CHK_(ptr);
				switch (tag >> 3) {
					// int32 result = 1;
				case 1:
					if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
						result_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
						CHK_(ptr);
					}
					else goto handle_unusual;
					continue;
					// repeated .frmpub.protocc.ServerInfo sifs = 2;
				case 2:
					if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
						ptr -= 1;
						do {
							ptr += 1;
							ptr = ctx->ParseMessage(_internal_add_sifs(), ptr);
							CHK_(ptr);
							if (!ctx->DataAvailable(ptr)) break;
						} while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
					}
					else goto handle_unusual;
					continue;
				default:
				{
				handle_unusual:
					if ((tag & 7) == 4 || tag == 0) {
						ctx->SetLastTag(tag);
						goto success;
					}
					ptr = UnknownFieldParse(tag,
						_internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
						ptr, ctx);
					CHK_(ptr != nullptr);
					continue;
				}
				}  // switch
			}  // while
		success:
			return ptr;
		failure:
			ptr = nullptr;
			goto success;
#undef CHK_
		}

		::PROTOBUF_NAMESPACE_ID::uint8* register_gate_world_s::_InternalSerialize(
			::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
			// @@protoc_insertion_point(serialize_to_array_start:frmpub.protocc.register_gate_world_s)
			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			(void)cached_has_bits;

			// int32 result = 1;
			if (this->result() != 0) {
				target = stream->EnsureSpace(target);
				target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_result(), target);
			}

			// repeated .frmpub.protocc.ServerInfo sifs = 2;
			for (unsigned int i = 0,
				n = static_cast<unsigned int>(this->_internal_sifs_size()); i < n; i++) {
				target = stream->EnsureSpace(target);
				target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
					InternalWriteMessage(2, this->_internal_sifs(i), target, stream);
			}

			if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
				target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
					_internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
			}
			// @@protoc_insertion_point(serialize_to_array_end:frmpub.protocc.register_gate_world_s)
			return target;
		}

		size_t register_gate_world_s::ByteSizeLong() const {
			// @@protoc_insertion_point(message_byte_size_start:frmpub.protocc.register_gate_world_s)
			size_t total_size = 0;

			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			// Prevent compiler warnings about cached_has_bits being unused
			(void)cached_has_bits;

			// repeated .frmpub.protocc.ServerInfo sifs = 2;
			total_size += 1UL * this->_internal_sifs_size();
			for (const auto& msg : this->sifs_) {
				total_size +=
					::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
			}

			// int32 result = 1;
			if (this->result() != 0) {
				total_size += 1 +
					::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
						this->_internal_result());
			}

			if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
				return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
					_internal_metadata_, total_size, &_cached_size_);
			}
			int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
			SetCachedSize(cached_size);
			return total_size;
		}

		void register_gate_world_s::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
			// @@protoc_insertion_point(generalized_merge_from_start:frmpub.protocc.register_gate_world_s)
			GOOGLE_DCHECK_NE(&from, this);
			const register_gate_world_s* source =
				::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<register_gate_world_s>(
					&from);
			if (source == nullptr) {
				// @@protoc_insertion_point(generalized_merge_from_cast_fail:frmpub.protocc.register_gate_world_s)
				::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
			}
			else {
				// @@protoc_insertion_point(generalized_merge_from_cast_success:frmpub.protocc.register_gate_world_s)
				MergeFrom(*source);
			}
		}

		void register_gate_world_s::MergeFrom(const register_gate_world_s& from) {
			// @@protoc_insertion_point(class_specific_merge_from_start:frmpub.protocc.register_gate_world_s)
			GOOGLE_DCHECK_NE(&from, this);
			_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			(void)cached_has_bits;

			sifs_.MergeFrom(from.sifs_);
			if (from.result() != 0) {
				_internal_set_result(from._internal_result());
			}
		}

		void register_gate_world_s::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
			// @@protoc_insertion_point(generalized_copy_from_start:frmpub.protocc.register_gate_world_s)
			if (&from == this) return;
			Clear();
			MergeFrom(from);
		}

		void register_gate_world_s::CopyFrom(const register_gate_world_s& from) {
			// @@protoc_insertion_point(class_specific_copy_from_start:frmpub.protocc.register_gate_world_s)
			if (&from == this) return;
			Clear();
			MergeFrom(from);
		}

		bool register_gate_world_s::IsInitialized() const {
			return true;
		}

		void register_gate_world_s::InternalSwap(register_gate_world_s* other) {
			using std::swap;
			_internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
			sifs_.InternalSwap(&other->sifs_);
			swap(result_, other->result_);
		}

		::PROTOBUF_NAMESPACE_ID::Metadata register_gate_world_s::GetMetadata() const {
			return GetMetadataStatic();
		}


		// ===================================================================

		class register_gate_login_c::_Internal {
		public:
			static const ::frmpub::protocc::ServerInfo& sif(const register_gate_login_c* msg);
		};

		const ::frmpub::protocc::ServerInfo&
			register_gate_login_c::_Internal::sif(const register_gate_login_c* msg) {
			return *msg->sif_;
		}
		void register_gate_login_c::clear_sif() {
			if (GetArena() == nullptr && sif_ != nullptr) {
				delete sif_;
			}
			sif_ = nullptr;
		}
		register_gate_login_c::register_gate_login_c(::PROTOBUF_NAMESPACE_ID::Arena* arena)
			: ::PROTOBUF_NAMESPACE_ID::Message(arena) {
			SharedCtor();
			RegisterArenaDtor(arena);
			// @@protoc_insertion_point(arena_constructor:frmpub.protocc.register_gate_login_c)
		}
		register_gate_login_c::register_gate_login_c(const register_gate_login_c& from)
			: ::PROTOBUF_NAMESPACE_ID::Message() {
			_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
			if (from._internal_has_sif()) {
				sif_ = new ::frmpub::protocc::ServerInfo(*from.sif_);
			}
			else {
				sif_ = nullptr;
			}
			// @@protoc_insertion_point(copy_constructor:frmpub.protocc.register_gate_login_c)
		}

		void register_gate_login_c::SharedCtor() {
			sif_ = nullptr;
		}

		register_gate_login_c::~register_gate_login_c() {
			// @@protoc_insertion_point(destructor:frmpub.protocc.register_gate_login_c)
			SharedDtor();
			_internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
		}

		void register_gate_login_c::SharedDtor() {
			GOOGLE_DCHECK(GetArena() == nullptr);
			if (this != internal_default_instance()) delete sif_;
		}

		void register_gate_login_c::ArenaDtor(void* object) {
			register_gate_login_c* _this = reinterpret_cast<register_gate_login_c*>(object);
			(void)_this;
		}
		void register_gate_login_c::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
		}
		void register_gate_login_c::SetCachedSize(int size) const {
			_cached_size_.Set(size);
		}

		void register_gate_login_c::Clear() {
			// @@protoc_insertion_point(message_clear_start:frmpub.protocc.register_gate_login_c)
			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			// Prevent compiler warnings about cached_has_bits being unused
			(void)cached_has_bits;

			if (GetArena() == nullptr && sif_ != nullptr) {
				delete sif_;
			}
			sif_ = nullptr;
			_internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
		}

		const char* register_gate_login_c::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
			while (!ctx->Done(&ptr)) {
				::PROTOBUF_NAMESPACE_ID::uint32 tag;
				ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
				CHK_(ptr);
				switch (tag >> 3) {
					// .frmpub.protocc.ServerInfo sif = 1;
				case 1:
					if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
						ptr = ctx->ParseMessage(_internal_mutable_sif(), ptr);
						CHK_(ptr);
					}
					else goto handle_unusual;
					continue;
				default:
				{
				handle_unusual:
					if ((tag & 7) == 4 || tag == 0) {
						ctx->SetLastTag(tag);
						goto success;
					}
					ptr = UnknownFieldParse(tag,
						_internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
						ptr, ctx);
					CHK_(ptr != nullptr);
					continue;
				}
				}  // switch
			}  // while
		success:
			return ptr;
		failure:
			ptr = nullptr;
			goto success;
#undef CHK_
		}

		::PROTOBUF_NAMESPACE_ID::uint8* register_gate_login_c::_InternalSerialize(
			::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
			// @@protoc_insertion_point(serialize_to_array_start:frmpub.protocc.register_gate_login_c)
			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			(void)cached_has_bits;

			// .frmpub.protocc.ServerInfo sif = 1;
			if (this->has_sif()) {
				target = stream->EnsureSpace(target);
				target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
					InternalWriteMessage(
						1, _Internal::sif(this), target, stream);
			}

			if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
				target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
					_internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
			}
			// @@protoc_insertion_point(serialize_to_array_end:frmpub.protocc.register_gate_login_c)
			return target;
		}

		size_t register_gate_login_c::ByteSizeLong() const {
			// @@protoc_insertion_point(message_byte_size_start:frmpub.protocc.register_gate_login_c)
			size_t total_size = 0;

			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			// Prevent compiler warnings about cached_has_bits being unused
			(void)cached_has_bits;

			// .frmpub.protocc.ServerInfo sif = 1;
			if (this->has_sif()) {
				total_size += 1 +
					::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
						*sif_);
			}

			if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
				return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
					_internal_metadata_, total_size, &_cached_size_);
			}
			int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
			SetCachedSize(cached_size);
			return total_size;
		}

		void register_gate_login_c::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
			// @@protoc_insertion_point(generalized_merge_from_start:frmpub.protocc.register_gate_login_c)
			GOOGLE_DCHECK_NE(&from, this);
			const register_gate_login_c* source =
				::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<register_gate_login_c>(
					&from);
			if (source == nullptr) {
				// @@protoc_insertion_point(generalized_merge_from_cast_fail:frmpub.protocc.register_gate_login_c)
				::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
			}
			else {
				// @@protoc_insertion_point(generalized_merge_from_cast_success:frmpub.protocc.register_gate_login_c)
				MergeFrom(*source);
			}
		}

		void register_gate_login_c::MergeFrom(const register_gate_login_c& from) {
			// @@protoc_insertion_point(class_specific_merge_from_start:frmpub.protocc.register_gate_login_c)
			GOOGLE_DCHECK_NE(&from, this);
			_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			(void)cached_has_bits;

			if (from.has_sif()) {
				_internal_mutable_sif()->::frmpub::protocc::ServerInfo::MergeFrom(from._internal_sif());
			}
		}

		void register_gate_login_c::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
			// @@protoc_insertion_point(generalized_copy_from_start:frmpub.protocc.register_gate_login_c)
			if (&from == this) return;
			Clear();
			MergeFrom(from);
		}

		void register_gate_login_c::CopyFrom(const register_gate_login_c& from) {
			// @@protoc_insertion_point(class_specific_copy_from_start:frmpub.protocc.register_gate_login_c)
			if (&from == this) return;
			Clear();
			MergeFrom(from);
		}

		bool register_gate_login_c::IsInitialized() const {
			return true;
		}

		void register_gate_login_c::InternalSwap(register_gate_login_c* other) {
			using std::swap;
			_internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
			swap(sif_, other->sif_);
		}

		::PROTOBUF_NAMESPACE_ID::Metadata register_gate_login_c::GetMetadata() const {
			return GetMetadataStatic();
		}


		// ===================================================================

		class register_gate_login_s::_Internal {
		public:
		};

		register_gate_login_s::register_gate_login_s(::PROTOBUF_NAMESPACE_ID::Arena* arena)
			: ::PROTOBUF_NAMESPACE_ID::Message(arena) {
			SharedCtor();
			RegisterArenaDtor(arena);
			// @@protoc_insertion_point(arena_constructor:frmpub.protocc.register_gate_login_s)
		}
		register_gate_login_s::register_gate_login_s(const register_gate_login_s& from)
			: ::PROTOBUF_NAMESPACE_ID::Message() {
			_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
			result_ = from.result_;
			// @@protoc_insertion_point(copy_constructor:frmpub.protocc.register_gate_login_s)
		}

		void register_gate_login_s::SharedCtor() {
			result_ = 0;
		}

		register_gate_login_s::~register_gate_login_s() {
			// @@protoc_insertion_point(destructor:frmpub.protocc.register_gate_login_s)
			SharedDtor();
			_internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
		}

		void register_gate_login_s::SharedDtor() {
			GOOGLE_DCHECK(GetArena() == nullptr);
		}

		void register_gate_login_s::ArenaDtor(void* object) {
			register_gate_login_s* _this = reinterpret_cast<register_gate_login_s*>(object);
			(void)_this;
		}
		void register_gate_login_s::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
		}
		void register_gate_login_s::SetCachedSize(int size) const {
			_cached_size_.Set(size);
		}

		void register_gate_login_s::Clear() {
			// @@protoc_insertion_point(message_clear_start:frmpub.protocc.register_gate_login_s)
			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			// Prevent compiler warnings about cached_has_bits being unused
			(void)cached_has_bits;

			result_ = 0;
			_internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
		}

		const char* register_gate_login_s::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
			while (!ctx->Done(&ptr)) {
				::PROTOBUF_NAMESPACE_ID::uint32 tag;
				ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
				CHK_(ptr);
				switch (tag >> 3) {
					// int32 result = 1;
				case 1:
					if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
						result_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
						CHK_(ptr);
					}
					else goto handle_unusual;
					continue;
				default:
				{
				handle_unusual:
					if ((tag & 7) == 4 || tag == 0) {
						ctx->SetLastTag(tag);
						goto success;
					}
					ptr = UnknownFieldParse(tag,
						_internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
						ptr, ctx);
					CHK_(ptr != nullptr);
					continue;
				}
				}  // switch
			}  // while
		success:
			return ptr;
		failure:
			ptr = nullptr;
			goto success;
#undef CHK_
		}

		::PROTOBUF_NAMESPACE_ID::uint8* register_gate_login_s::_InternalSerialize(
			::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
			// @@protoc_insertion_point(serialize_to_array_start:frmpub.protocc.register_gate_login_s)
			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			(void)cached_has_bits;

			// int32 result = 1;
			if (this->result() != 0) {
				target = stream->EnsureSpace(target);
				target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_result(), target);
			}

			if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
				target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
					_internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
			}
			// @@protoc_insertion_point(serialize_to_array_end:frmpub.protocc.register_gate_login_s)
			return target;
		}

		size_t register_gate_login_s::ByteSizeLong() const {
			// @@protoc_insertion_point(message_byte_size_start:frmpub.protocc.register_gate_login_s)
			size_t total_size = 0;

			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			// Prevent compiler warnings about cached_has_bits being unused
			(void)cached_has_bits;

			// int32 result = 1;
			if (this->result() != 0) {
				total_size += 1 +
					::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
						this->_internal_result());
			}

			if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
				return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
					_internal_metadata_, total_size, &_cached_size_);
			}
			int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
			SetCachedSize(cached_size);
			return total_size;
		}

		void register_gate_login_s::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
			// @@protoc_insertion_point(generalized_merge_from_start:frmpub.protocc.register_gate_login_s)
			GOOGLE_DCHECK_NE(&from, this);
			const register_gate_login_s* source =
				::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<register_gate_login_s>(
					&from);
			if (source == nullptr) {
				// @@protoc_insertion_point(generalized_merge_from_cast_fail:frmpub.protocc.register_gate_login_s)
				::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
			}
			else {
				// @@protoc_insertion_point(generalized_merge_from_cast_success:frmpub.protocc.register_gate_login_s)
				MergeFrom(*source);
			}
		}

		void register_gate_login_s::MergeFrom(const register_gate_login_s& from) {
			// @@protoc_insertion_point(class_specific_merge_from_start:frmpub.protocc.register_gate_login_s)
			GOOGLE_DCHECK_NE(&from, this);
			_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			(void)cached_has_bits;

			if (from.result() != 0) {
				_internal_set_result(from._internal_result());
			}
		}

		void register_gate_login_s::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
			// @@protoc_insertion_point(generalized_copy_from_start:frmpub.protocc.register_gate_login_s)
			if (&from == this) return;
			Clear();
			MergeFrom(from);
		}

		void register_gate_login_s::CopyFrom(const register_gate_login_s& from) {
			// @@protoc_insertion_point(class_specific_copy_from_start:frmpub.protocc.register_gate_login_s)
			if (&from == this) return;
			Clear();
			MergeFrom(from);
		}

		bool register_gate_login_s::IsInitialized() const {
			return true;
		}

		void register_gate_login_s::InternalSwap(register_gate_login_s* other) {
			using std::swap;
			_internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
			swap(result_, other->result_);
		}

		::PROTOBUF_NAMESPACE_ID::Metadata register_gate_login_s::GetMetadata() const {
			return GetMetadataStatic();
		}


		// ===================================================================

		class register_gate_game_c::_Internal {
		public:
			static const ::frmpub::protocc::ServerInfo& sif(const register_gate_game_c* msg);
		};

		const ::frmpub::protocc::ServerInfo&
			register_gate_game_c::_Internal::sif(const register_gate_game_c* msg) {
			return *msg->sif_;
		}
		void register_gate_game_c::clear_sif() {
			if (GetArena() == nullptr && sif_ != nullptr) {
				delete sif_;
			}
			sif_ = nullptr;
		}
		register_gate_game_c::register_gate_game_c(::PROTOBUF_NAMESPACE_ID::Arena* arena)
			: ::PROTOBUF_NAMESPACE_ID::Message(arena) {
			SharedCtor();
			RegisterArenaDtor(arena);
			// @@protoc_insertion_point(arena_constructor:frmpub.protocc.register_gate_game_c)
		}
		register_gate_game_c::register_gate_game_c(const register_gate_game_c& from)
			: ::PROTOBUF_NAMESPACE_ID::Message() {
			_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
			if (from._internal_has_sif()) {
				sif_ = new ::frmpub::protocc::ServerInfo(*from.sif_);
			}
			else {
				sif_ = nullptr;
			}
			// @@protoc_insertion_point(copy_constructor:frmpub.protocc.register_gate_game_c)
		}

		void register_gate_game_c::SharedCtor() {
			sif_ = nullptr;
		}

		register_gate_game_c::~register_gate_game_c() {
			// @@protoc_insertion_point(destructor:frmpub.protocc.register_gate_game_c)
			SharedDtor();
			_internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
		}

		void register_gate_game_c::SharedDtor() {
			GOOGLE_DCHECK(GetArena() == nullptr);
			if (this != internal_default_instance()) delete sif_;
		}

		void register_gate_game_c::ArenaDtor(void* object) {
			register_gate_game_c* _this = reinterpret_cast<register_gate_game_c*>(object);
			(void)_this;
		}
		void register_gate_game_c::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
		}
		void register_gate_game_c::SetCachedSize(int size) const {
			_cached_size_.Set(size);
		}

		void register_gate_game_c::Clear() {
			// @@protoc_insertion_point(message_clear_start:frmpub.protocc.register_gate_game_c)
			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			// Prevent compiler warnings about cached_has_bits being unused
			(void)cached_has_bits;

			if (GetArena() == nullptr && sif_ != nullptr) {
				delete sif_;
			}
			sif_ = nullptr;
			_internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
		}

		const char* register_gate_game_c::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
			while (!ctx->Done(&ptr)) {
				::PROTOBUF_NAMESPACE_ID::uint32 tag;
				ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
				CHK_(ptr);
				switch (tag >> 3) {
					// .frmpub.protocc.ServerInfo sif = 1;
				case 1:
					if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
						ptr = ctx->ParseMessage(_internal_mutable_sif(), ptr);
						CHK_(ptr);
					}
					else goto handle_unusual;
					continue;
				default:
				{
				handle_unusual:
					if ((tag & 7) == 4 || tag == 0) {
						ctx->SetLastTag(tag);
						goto success;
					}
					ptr = UnknownFieldParse(tag,
						_internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
						ptr, ctx);
					CHK_(ptr != nullptr);
					continue;
				}
				}  // switch
			}  // while
		success:
			return ptr;
		failure:
			ptr = nullptr;
			goto success;
#undef CHK_
		}

		::PROTOBUF_NAMESPACE_ID::uint8* register_gate_game_c::_InternalSerialize(
			::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
			// @@protoc_insertion_point(serialize_to_array_start:frmpub.protocc.register_gate_game_c)
			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			(void)cached_has_bits;

			// .frmpub.protocc.ServerInfo sif = 1;
			if (this->has_sif()) {
				target = stream->EnsureSpace(target);
				target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
					InternalWriteMessage(
						1, _Internal::sif(this), target, stream);
			}

			if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
				target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
					_internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
			}
			// @@protoc_insertion_point(serialize_to_array_end:frmpub.protocc.register_gate_game_c)
			return target;
		}

		size_t register_gate_game_c::ByteSizeLong() const {
			// @@protoc_insertion_point(message_byte_size_start:frmpub.protocc.register_gate_game_c)
			size_t total_size = 0;

			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			// Prevent compiler warnings about cached_has_bits being unused
			(void)cached_has_bits;

			// .frmpub.protocc.ServerInfo sif = 1;
			if (this->has_sif()) {
				total_size += 1 +
					::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
						*sif_);
			}

			if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
				return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
					_internal_metadata_, total_size, &_cached_size_);
			}
			int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
			SetCachedSize(cached_size);
			return total_size;
		}

		void register_gate_game_c::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
			// @@protoc_insertion_point(generalized_merge_from_start:frmpub.protocc.register_gate_game_c)
			GOOGLE_DCHECK_NE(&from, this);
			const register_gate_game_c* source =
				::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<register_gate_game_c>(
					&from);
			if (source == nullptr) {
				// @@protoc_insertion_point(generalized_merge_from_cast_fail:frmpub.protocc.register_gate_game_c)
				::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
			}
			else {
				// @@protoc_insertion_point(generalized_merge_from_cast_success:frmpub.protocc.register_gate_game_c)
				MergeFrom(*source);
			}
		}

		void register_gate_game_c::MergeFrom(const register_gate_game_c& from) {
			// @@protoc_insertion_point(class_specific_merge_from_start:frmpub.protocc.register_gate_game_c)
			GOOGLE_DCHECK_NE(&from, this);
			_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			(void)cached_has_bits;

			if (from.has_sif()) {
				_internal_mutable_sif()->::frmpub::protocc::ServerInfo::MergeFrom(from._internal_sif());
			}
		}

		void register_gate_game_c::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
			// @@protoc_insertion_point(generalized_copy_from_start:frmpub.protocc.register_gate_game_c)
			if (&from == this) return;
			Clear();
			MergeFrom(from);
		}

		void register_gate_game_c::CopyFrom(const register_gate_game_c& from) {
			// @@protoc_insertion_point(class_specific_copy_from_start:frmpub.protocc.register_gate_game_c)
			if (&from == this) return;
			Clear();
			MergeFrom(from);
		}

		bool register_gate_game_c::IsInitialized() const {
			return true;
		}

		void register_gate_game_c::InternalSwap(register_gate_game_c* other) {
			using std::swap;
			_internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
			swap(sif_, other->sif_);
		}

		::PROTOBUF_NAMESPACE_ID::Metadata register_gate_game_c::GetMetadata() const {
			return GetMetadataStatic();
		}


		// ===================================================================

		class register_gate_game_s::_Internal {
		public:
		};

		register_gate_game_s::register_gate_game_s(::PROTOBUF_NAMESPACE_ID::Arena* arena)
			: ::PROTOBUF_NAMESPACE_ID::Message(arena) {
			SharedCtor();
			RegisterArenaDtor(arena);
			// @@protoc_insertion_point(arena_constructor:frmpub.protocc.register_gate_game_s)
		}
		register_gate_game_s::register_gate_game_s(const register_gate_game_s& from)
			: ::PROTOBUF_NAMESPACE_ID::Message() {
			_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
			result_ = from.result_;
			// @@protoc_insertion_point(copy_constructor:frmpub.protocc.register_gate_game_s)
		}

		void register_gate_game_s::SharedCtor() {
			result_ = 0;
		}

		register_gate_game_s::~register_gate_game_s() {
			// @@protoc_insertion_point(destructor:frmpub.protocc.register_gate_game_s)
			SharedDtor();
			_internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
		}

		void register_gate_game_s::SharedDtor() {
			GOOGLE_DCHECK(GetArena() == nullptr);
		}

		void register_gate_game_s::ArenaDtor(void* object) {
			register_gate_game_s* _this = reinterpret_cast<register_gate_game_s*>(object);
			(void)_this;
		}
		void register_gate_game_s::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
		}
		void register_gate_game_s::SetCachedSize(int size) const {
			_cached_size_.Set(size);
		}

		void register_gate_game_s::Clear() {
			// @@protoc_insertion_point(message_clear_start:frmpub.protocc.register_gate_game_s)
			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			// Prevent compiler warnings about cached_has_bits being unused
			(void)cached_has_bits;

			result_ = 0;
			_internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
		}

		const char* register_gate_game_s::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
			while (!ctx->Done(&ptr)) {
				::PROTOBUF_NAMESPACE_ID::uint32 tag;
				ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
				CHK_(ptr);
				switch (tag >> 3) {
					// int32 result = 1;
				case 1:
					if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
						result_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
						CHK_(ptr);
					}
					else goto handle_unusual;
					continue;
				default:
				{
				handle_unusual:
					if ((tag & 7) == 4 || tag == 0) {
						ctx->SetLastTag(tag);
						goto success;
					}
					ptr = UnknownFieldParse(tag,
						_internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
						ptr, ctx);
					CHK_(ptr != nullptr);
					continue;
				}
				}  // switch
			}  // while
		success:
			return ptr;
		failure:
			ptr = nullptr;
			goto success;
#undef CHK_
		}

		::PROTOBUF_NAMESPACE_ID::uint8* register_gate_game_s::_InternalSerialize(
			::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
			// @@protoc_insertion_point(serialize_to_array_start:frmpub.protocc.register_gate_game_s)
			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			(void)cached_has_bits;

			// int32 result = 1;
			if (this->result() != 0) {
				target = stream->EnsureSpace(target);
				target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_result(), target);
			}

			if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
				target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
					_internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
			}
			// @@protoc_insertion_point(serialize_to_array_end:frmpub.protocc.register_gate_game_s)
			return target;
		}

		size_t register_gate_game_s::ByteSizeLong() const {
			// @@protoc_insertion_point(message_byte_size_start:frmpub.protocc.register_gate_game_s)
			size_t total_size = 0;

			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			// Prevent compiler warnings about cached_has_bits being unused
			(void)cached_has_bits;

			// int32 result = 1;
			if (this->result() != 0) {
				total_size += 1 +
					::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
						this->_internal_result());
			}

			if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
				return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
					_internal_metadata_, total_size, &_cached_size_);
			}
			int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
			SetCachedSize(cached_size);
			return total_size;
		}

		void register_gate_game_s::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
			// @@protoc_insertion_point(generalized_merge_from_start:frmpub.protocc.register_gate_game_s)
			GOOGLE_DCHECK_NE(&from, this);
			const register_gate_game_s* source =
				::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<register_gate_game_s>(
					&from);
			if (source == nullptr) {
				// @@protoc_insertion_point(generalized_merge_from_cast_fail:frmpub.protocc.register_gate_game_s)
				::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
			}
			else {
				// @@protoc_insertion_point(generalized_merge_from_cast_success:frmpub.protocc.register_gate_game_s)
				MergeFrom(*source);
			}
		}

		void register_gate_game_s::MergeFrom(const register_gate_game_s& from) {
			// @@protoc_insertion_point(class_specific_merge_from_start:frmpub.protocc.register_gate_game_s)
			GOOGLE_DCHECK_NE(&from, this);
			_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			(void)cached_has_bits;

			if (from.result() != 0) {
				_internal_set_result(from._internal_result());
			}
		}

		void register_gate_game_s::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
			// @@protoc_insertion_point(generalized_copy_from_start:frmpub.protocc.register_gate_game_s)
			if (&from == this) return;
			Clear();
			MergeFrom(from);
		}

		void register_gate_game_s::CopyFrom(const register_gate_game_s& from) {
			// @@protoc_insertion_point(class_specific_copy_from_start:frmpub.protocc.register_gate_game_s)
			if (&from == this) return;
			Clear();
			MergeFrom(from);
		}

		bool register_gate_game_s::IsInitialized() const {
			return true;
		}

		void register_gate_game_s::InternalSwap(register_gate_game_s* other) {
			using std::swap;
			_internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
			swap(result_, other->result_);
		}

		::PROTOBUF_NAMESPACE_ID::Metadata register_gate_game_s::GetMetadata() const {
			return GetMetadataStatic();
		}


		// ===================================================================

		class clioffline_gate_all_c::_Internal {
		public:
		};

		clioffline_gate_all_c::clioffline_gate_all_c(::PROTOBUF_NAMESPACE_ID::Arena* arena)
			: ::PROTOBUF_NAMESPACE_ID::Message(arena) {
			SharedCtor();
			RegisterArenaDtor(arena);
			// @@protoc_insertion_point(arena_constructor:frmpub.protocc.clioffline_gate_all_c)
		}
		clioffline_gate_all_c::clioffline_gate_all_c(const clioffline_gate_all_c& from)
			: ::PROTOBUF_NAMESPACE_ID::Message() {
			_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
			aid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
			if (!from._internal_aid().empty()) {
				aid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_aid(),
					GetArena());
			}
			ip_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
			if (!from._internal_ip().empty()) {
				ip_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_ip(),
					GetArena());
			}
			port_ = from.port_;
			// @@protoc_insertion_point(copy_constructor:frmpub.protocc.clioffline_gate_all_c)
		}

		void clioffline_gate_all_c::SharedCtor() {
			aid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
			ip_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
			port_ = 0;
		}

		clioffline_gate_all_c::~clioffline_gate_all_c() {
			// @@protoc_insertion_point(destructor:frmpub.protocc.clioffline_gate_all_c)
			SharedDtor();
			_internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
		}

		void clioffline_gate_all_c::SharedDtor() {
			GOOGLE_DCHECK(GetArena() == nullptr);
			aid_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
			ip_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
		}

		void clioffline_gate_all_c::ArenaDtor(void* object) {
			clioffline_gate_all_c* _this = reinterpret_cast<clioffline_gate_all_c*>(object);
			(void)_this;
		}
		void clioffline_gate_all_c::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
		}
		void clioffline_gate_all_c::SetCachedSize(int size) const {
			_cached_size_.Set(size);
		}

		void clioffline_gate_all_c::Clear() {
			// @@protoc_insertion_point(message_clear_start:frmpub.protocc.clioffline_gate_all_c)
			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			// Prevent compiler warnings about cached_has_bits being unused
			(void)cached_has_bits;

			aid_.ClearToEmpty();
			ip_.ClearToEmpty();
			port_ = 0;
			_internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
		}

		const char* clioffline_gate_all_c::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
			while (!ctx->Done(&ptr)) {
				::PROTOBUF_NAMESPACE_ID::uint32 tag;
				ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
				CHK_(ptr);
				switch (tag >> 3) {
					// string aid = 1;
				case 1:
					if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
						auto str = _internal_mutable_aid();
						ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
						CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "frmpub.protocc.clioffline_gate_all_c.aid"));
						CHK_(ptr);
					}
					else goto handle_unusual;
					continue;
					// string ip = 2;
				case 2:
					if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
						auto str = _internal_mutable_ip();
						ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
						CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "frmpub.protocc.clioffline_gate_all_c.ip"));
						CHK_(ptr);
					}
					else goto handle_unusual;
					continue;
					// int32 port = 3;
				case 3:
					if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
						port_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
						CHK_(ptr);
					}
					else goto handle_unusual;
					continue;
				default:
				{
				handle_unusual:
					if ((tag & 7) == 4 || tag == 0) {
						ctx->SetLastTag(tag);
						goto success;
					}
					ptr = UnknownFieldParse(tag,
						_internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
						ptr, ctx);
					CHK_(ptr != nullptr);
					continue;
				}
				}  // switch
			}  // while
		success:
			return ptr;
		failure:
			ptr = nullptr;
			goto success;
#undef CHK_
		}

		::PROTOBUF_NAMESPACE_ID::uint8* clioffline_gate_all_c::_InternalSerialize(
			::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
			// @@protoc_insertion_point(serialize_to_array_start:frmpub.protocc.clioffline_gate_all_c)
			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			(void)cached_has_bits;

			// string aid = 1;
			if (this->aid().size() > 0) {
				::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
					this->_internal_aid().data(), static_cast<int>(this->_internal_aid().length()),
					::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
					"frmpub.protocc.clioffline_gate_all_c.aid");
				target = stream->WriteStringMaybeAliased(
					1, this->_internal_aid(), target);
			}

			// string ip = 2;
			if (this->ip().size() > 0) {
				::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
					this->_internal_ip().data(), static_cast<int>(this->_internal_ip().length()),
					::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
					"frmpub.protocc.clioffline_gate_all_c.ip");
				target = stream->WriteStringMaybeAliased(
					2, this->_internal_ip(), target);
			}

			// int32 port = 3;
			if (this->port() != 0) {
				target = stream->EnsureSpace(target);
				target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_port(), target);
			}

			if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
				target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
					_internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
			}
			// @@protoc_insertion_point(serialize_to_array_end:frmpub.protocc.clioffline_gate_all_c)
			return target;
		}

		size_t clioffline_gate_all_c::ByteSizeLong() const {
			// @@protoc_insertion_point(message_byte_size_start:frmpub.protocc.clioffline_gate_all_c)
			size_t total_size = 0;

			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			// Prevent compiler warnings about cached_has_bits being unused
			(void)cached_has_bits;

			// string aid = 1;
			if (this->aid().size() > 0) {
				total_size += 1 +
					::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
						this->_internal_aid());
			}

			// string ip = 2;
			if (this->ip().size() > 0) {
				total_size += 1 +
					::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
						this->_internal_ip());
			}

			// int32 port = 3;
			if (this->port() != 0) {
				total_size += 1 +
					::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
						this->_internal_port());
			}

			if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
				return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
					_internal_metadata_, total_size, &_cached_size_);
			}
			int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
			SetCachedSize(cached_size);
			return total_size;
		}

		void clioffline_gate_all_c::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
			// @@protoc_insertion_point(generalized_merge_from_start:frmpub.protocc.clioffline_gate_all_c)
			GOOGLE_DCHECK_NE(&from, this);
			const clioffline_gate_all_c* source =
				::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<clioffline_gate_all_c>(
					&from);
			if (source == nullptr) {
				// @@protoc_insertion_point(generalized_merge_from_cast_fail:frmpub.protocc.clioffline_gate_all_c)
				::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
			}
			else {
				// @@protoc_insertion_point(generalized_merge_from_cast_success:frmpub.protocc.clioffline_gate_all_c)
				MergeFrom(*source);
			}
		}

		void clioffline_gate_all_c::MergeFrom(const clioffline_gate_all_c& from) {
			// @@protoc_insertion_point(class_specific_merge_from_start:frmpub.protocc.clioffline_gate_all_c)
			GOOGLE_DCHECK_NE(&from, this);
			_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
			::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
			(void)cached_has_bits;

			if (from.aid().size() > 0) {
				_internal_set_aid(from._internal_aid());
			}
			if (from.ip().size() > 0) {
				_internal_set_ip(from._internal_ip());
			}
			if (from.port() != 0) {
				_internal_set_port(from._internal_port());
			}
		}

		void clioffline_gate_all_c::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
			// @@protoc_insertion_point(generalized_copy_from_start:frmpub.protocc.clioffline_gate_all_c)
			if (&from == this) return;
			Clear();
			MergeFrom(from);
		}

		void clioffline_gate_all_c::CopyFrom(const clioffline_gate_all_c& from) {
			// @@protoc_insertion_point(class_specific_copy_from_start:frmpub.protocc.clioffline_gate_all_c)
			if (&from == this) return;
			Clear();
			MergeFrom(from);
		}

		bool clioffline_gate_all_c::IsInitialized() const {
			return true;
		}

		void clioffline_gate_all_c::InternalSwap(clioffline_gate_all_c* other) {
			using std::swap;
			_internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
			aid_.Swap(&other->aid_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
			ip_.Swap(&other->ip_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
			swap(port_, other->port_);
		}

		::PROTOBUF_NAMESPACE_ID::Metadata clioffline_gate_all_c::GetMetadata() const {
			return GetMetadataStatic();
		}


		// @@protoc_insertion_point(namespace_scope)
	}  // namespace protocc
}  // namespace frmpub
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE::frmpub::protocc::register_gate_dbvisit_c* Arena::CreateMaybeMessage< ::frmpub::protocc::register_gate_dbvisit_c >(Arena* arena) {
	return Arena::CreateMessageInternal< ::frmpub::protocc::register_gate_dbvisit_c >(arena);
}
template<> PROTOBUF_NOINLINE::frmpub::protocc::register_gate_dbvisit_s* Arena::CreateMaybeMessage< ::frmpub::protocc::register_gate_dbvisit_s >(Arena* arena) {
	return Arena::CreateMessageInternal< ::frmpub::protocc::register_gate_dbvisit_s >(arena);
}
template<> PROTOBUF_NOINLINE::frmpub::protocc::register_gate_world_c* Arena::CreateMaybeMessage< ::frmpub::protocc::register_gate_world_c >(Arena* arena) {
	return Arena::CreateMessageInternal< ::frmpub::protocc::register_gate_world_c >(arena);
}
template<> PROTOBUF_NOINLINE::frmpub::protocc::register_gate_world_s* Arena::CreateMaybeMessage< ::frmpub::protocc::register_gate_world_s >(Arena* arena) {
	return Arena::CreateMessageInternal< ::frmpub::protocc::register_gate_world_s >(arena);
}
template<> PROTOBUF_NOINLINE::frmpub::protocc::register_gate_login_c* Arena::CreateMaybeMessage< ::frmpub::protocc::register_gate_login_c >(Arena* arena) {
	return Arena::CreateMessageInternal< ::frmpub::protocc::register_gate_login_c >(arena);
}
template<> PROTOBUF_NOINLINE::frmpub::protocc::register_gate_login_s* Arena::CreateMaybeMessage< ::frmpub::protocc::register_gate_login_s >(Arena* arena) {
	return Arena::CreateMessageInternal< ::frmpub::protocc::register_gate_login_s >(arena);
}
template<> PROTOBUF_NOINLINE::frmpub::protocc::register_gate_game_c* Arena::CreateMaybeMessage< ::frmpub::protocc::register_gate_game_c >(Arena* arena) {
	return Arena::CreateMessageInternal< ::frmpub::protocc::register_gate_game_c >(arena);
}
template<> PROTOBUF_NOINLINE::frmpub::protocc::register_gate_game_s* Arena::CreateMaybeMessage< ::frmpub::protocc::register_gate_game_s >(Arena* arena) {
	return Arena::CreateMessageInternal< ::frmpub::protocc::register_gate_game_s >(arena);
}
template<> PROTOBUF_NOINLINE::frmpub::protocc::clioffline_gate_all_c* Arena::CreateMaybeMessage< ::frmpub::protocc::clioffline_gate_all_c >(Arena* arena) {
	return Arena::CreateMessageInternal< ::frmpub::protocc::clioffline_gate_all_c >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
